### PR TITLE
Fix propagule overgrowth

### PR DESCRIPTION
**Pull request by mahss-io**
This seems to mitigate some of the issue, as some propagule of newly generated mangrove tress generate in valid growing location. This is based on a brief test this morning. Will do a bit more testing later today when I get the time.

Let me know any updates I might need to make.

### CODE REVIEW

**Comment by mahss-io** [comment]
Also linking #24

**Comment by InZan17** [comment]
The canGrow function is used whenever bone meal is applied to the sapling and also has a random result, so it can't be used like this. Otherwise, valid saplings will only simulate 45% of the time.

You might have to create a new mixin for the propagule and override the canSimulateRandTicks function and then add the extra checks the propagule has.

**Comment by mahss-io** [comment]
Thanks @InZan17.
I believe I created that new mixin properly and am having it extend your SaplingMixin then calling back to the super for the simulation and generation.

According to the [wiki](https://minecraft.wiki/w/Mangrove_Propagule#Usage) they can't grow into tress so that's what I am going with. 😆 
> A hanging mangrove propagule cannot grow into a tree.

**Comment by mahss-io** [comment]
Something like that?
I do now see the implementation for SimulateChunkBlocks implements the AbstractBlockMixin/AbstractBlock class (which I guess is more so AbstractBlock implementing SimulateChunkBlocks? Thats where the mixin stuff looses me) which all Block are extended from.

**Comment by InZan17** [comment]
Yes that's perfect. Thank you for the pull request!

**Comment by mahss-io** [comment]
Thanks you for the feedback and letting me learn a bit!

**Comment by DarianLStephens** [comment]
I saw this issue in the changelog, and am so sad there aren't any screenshots.

**Pull request merged**
